services:
  project1:
    image: php:8.1-apache
    container_name: project1
    volumes:
      - ./project1:/var/www/html
    ports:
      - "8081:80"
      
  project2:
    image: php:8.1-apache  
    container_name: project2
    volumes:
      - ./project2:/var/www/html
    ports:
      - "8082:80"
      
  project3:
    image: php:8.1-apache
    container_name: project3  
    volumes:
      - ./project3:/var/www/html
    ports:
      - "8083:80"