services:
  project1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project1
    volumes:
      - ./mirtsvetov/mirtsvetov.ru/public_html:/var/www/html
    ports:
      - "8081:80"